name: ehi_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: './assets/fonts/montserrat/Montserrat-Regular.ttf'
        - asset: './assets/fonts/montserrat/Montserrat-Italic.ttf'
          style: italic
        - asset: './assets\fonts\montserrat\Montserrat-SemiBold.ttf'
          weight: 700
  assets:
    - ./assets/images/
    - settings.env

